version: '3.9'

services:
  database:
    image: postgres
    container_name: "database"
    restart: unless-stopped
    env_file:
      - ./website/backend/server/.env
    ports:
      - "5432:5432"
    networks:
      - transnet
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./website/backend
    depends_on:
      - "database"
    container_name: "backend"
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "8080:8080"
      - "8100:8100"
    networks:
      - transnet
    volumes:
      - backend_data:/server/uploads/

  frontend:
    build:
      context: ./website/frontend
    depends_on:
      - "backend"
    container_name: "frontend"
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - transnet

networks:
  transnet:

volumes:
  db_data:
    name: dbdata 
  backend_data:
    name: backdata
